# Generated by Django 5.0.4 on 2024-04-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
